INSERT INTO
    role (label)
VALUES
    ('Administrateur'),
    ('Utilisateur');

INSERT INTO
    permission (label)
VALUES
    ('section:admin'),
    ('admin-section:users'),
    ('user:view-own'),
    ('user:view-all'),
    ('user:create'),
    ('user:update-own'),
    ('user:update-all'),
    ('user:delete-own'),
    ('user:delete-all'),
    ('admin-section:authorizations'),
    ('role-permission:view-all'),
    ('role-permission:create'),
    ('role-permission:delete-all'),
    ('permission:create'),
    ('role:create'),
    ('section:calendars'),
    ('calendar:view-own'),
    ('calendar:create'),
    ('calendar:update-own'),
    ('calendar:delete-own'),
    ('calendar:view-invited-to'),
    ('calendar:view-all'),
    ('calendar:update-all'),
    ('calendar:delete-all'),
    ('section:kanbans'),
    ('kanban:view-own'),
    ('kanban:create'),
    ('kanban:update-own'),
    ('kanban:delete-own'),
    ('kanban:view-invited-to'),
    ('kanban:view-all'),
    ('kanban:update-all'),
    ('kanban:delete-all'),
    ('kanban:invite-user'),
    ('kanban:delete-user'),
    ('kanban:kick-user'),
    ('list:create'),
    ('list:update-own'),
    ('list:delete-own'),
    ('list:update-all'),
    ('list:delete-all'),
    ('task:create'),
    ('task:move-own'),
    ('task:update-own'),
    ('task:delete-own'),
    ('task:move-all'),
    ('task:update-all'),
    ('task:delete-all'),
    ('task:assign-self'),
    ('task:unassign-self'),
    ('calendar:invite-user'),
    ('calendar:delete-user'),
    ('calendar:kick-user'),
    ('schedule:create'),
    ('schedule:update-own'),
    ('schedule:delete-own'),
    ('schedule:update-all'),
    ('schedule:delete-all');

INSERT INTO
    role_permission (role_id, permission_id)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10),
    (1, 11),
    (1, 12),
    (1, 13),
    (1, 14),
    (1, 15),
    (1, 16),
    (1, 17),
    (1, 18),
    (1, 19),
    (1, 20),
    (1, 21),
    (1, 22),
    (1, 23),
    (1, 24),
    (1, 25),
    (1, 26),
    (1, 27),
    (1, 28),
    (1, 29),
    (1, 30),
    (1, 31),
    (1, 32),
    (1, 33),
    (2, 3),
    (2, 4),
    (2, 6),
    (2, 8),
    (2, 16),
    (2, 17),
    (2, 18),
    (2, 19),
    (2, 20),
    (2, 21),
    (2, 25),
    (2, 26),
    (2, 27),
    (2, 28),
    (2, 29),
    (2, 30);
