-- KANBAN PERMISSIONS
DROP TABLE IF EXISTS kanban_invitation;

DROP TABLE IF EXISTS user_kanban_role;

DROP TABLE IF EXISTS kanban_role_permission;

DROP TABLE IF EXISTS kanban_role;

-- KANBAN
DROP TABLE IF EXISTS task_assignee;

DROP TABLE IF EXISTS task;

DROP TABLE IF EXISTS list;

DROP TABLE IF EXISTS shared_kanban;

DROP TABLE IF EXISTS kanban;

-- CALENDAR PERMISSIONS
DROP TABLE IF EXISTS user_calendar_role;

DROP TABLE IF EXISTS calendar_role_permission;

DROP TABLE IF EXISTS calendar_role;

-- CALENDAR
DROP TABLE IF EXISTS schedule;

DROP TABLE IF EXISTS shared_calendar;

DROP TABLE IF EXISTS calendar;

-- USER
DROP TABLE IF EXISTS session;

DROP TABLE IF EXISTS app_user;

-- ROLE PERMISSIONS
DROP TABLE IF EXISTS role_permission;

DROP TABLE IF EXISTS permission;

DROP TABLE IF EXISTS role;
